spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200

  datasource:
    url: jdbc:postgresql://localhost:5432/CustomAnalytics
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
